### ISSUE TITLE
Possible to cleanup highlights file from BOOX?

### ISSUE THREAD

**Issue by zenminimalist** [wangandi520/ClippingsToMarkdown#1]
Is there a way this code can go from this:

_Reading Notes*|*<<Alice's Adventures in Wonderland>>
null

Time：2022-02-20 14:53
【Original Text】miles I've fallen by this time?" she said aloud. "I must be getting somewhere near the centre of the earth. Let me see: that would be four thousand miles down. I think—" (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a very good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over) "—yes, that's about the right distance—but then I wonder what Latitude or Longitude I've got to?" (Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.) 
Presently she began again
【Annotations】
【Page Number】11
-------------------_

To a cleaned-up version in markdown like this:

_Alice's Adventures in Wonderland

was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, "Oh dear! Oh dear! I shall be too late!" (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat_

Maybe this code [here](https://github.com/rc2dev/fyodor) could help, although I believe it's just for Kindle?

**Comment by wangandi520** [comment]
hi,do you need a new form to markdown or some bugs in old script? it is easy  to program a new script base on old py script. but i can not see the differents or relations between this two paragraphs, maybe you can write the old form and what you want in markdown more clearly. like make a old.txt and new.md, i can make a new py script for you.

**Comment by zenminimalist** [comment]
Sorry, if it wasn't clear. This is how the Boox device gives you the highlights in form of a txt file:

Reading Notes*|*<<Alice's Adventures in Wonderland>>
null

Time：2022-02-20 14:53
【Original Text】miles I've fallen by this time?" she said aloud. "I must be getting somewhere near the centre of the earth. Let me see: that would be four thousand miles down. I think—" (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a very good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over) "—yes, that's about the right distance—but then I wonder what Latitude or Longitude I've got to?" (Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.) Presently she began again
【Annotations】
【Page Number】11
'-------------------

This format or highlight txt file includes unnecessary things that I don't want, such as <<, Time：2022-02-20 14:53, 【Original Text】,【Annotations】【Page Number】11, -------------------

So I'm looking just for a clean list of highlights in md format. So it should look like this format: 

Title: Alice's Adventures in Wonderland
Author: Lewis Carroll

miles I've fallen by this time?" she said aloud. "I must be getting somewhere near the centre of the earth. Let me see: that would be four thousand miles down. I think—" (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a very good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over) "—yes, that's about the right distance—but then I wonder what Latitude or Longitude I've got to?" (Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.) Presently she began again

t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.

Essentially each highlight should be on a separate line without any timestamps, special characters etc.

**Comment by wangandi520** [comment]
ok, please check BooxLocalInternational.py

i have tested. but there is only one highlight of books, i think it worked well

if you want show time and other infomations , modify line 43-48

**Comment by zenminimalist** [comment]
I tried the following command via Mac terminal: 

`python3 BooxLocalInternational.py /Users/David/Downloads/ClippingsToMarkdown/My\ Clippings.txt`

but get **no** error. I tried searching fro the md file, but didn't find one. Any ideas?

**Comment by wangandi520** [comment]
try new version i have just updated

**Comment by zenminimalist** [comment]
谢谢你! 对不起, 我的中文不好 😞 That did work this time 😊

I'm not sure if Boox devices output the author name (as I've seen multiple Boox files with "null"), but it would be cool if the md output file added the following: 

#Alice's Adventures in Wonderland (this is already the case ✅)
 
**Book:** Alice's Adventures in Wonderland
**Author:**

So it adds the name of the book and author directly after the main title. 

BTW, I removed the ">" on line 52, so it outputs a clean passage for highlight on a seperate paragraph.

**Comment by wangandi520** [comment]
book and author added, but i think it is duplicated

**Comment by zenminimalist** [comment]
Worked perfectly. I didn't see the book and author duplicated. I even tried adding an author and that too, works 👍🏼

**Comment by zenminimalist** [comment]
Before (Alice in Wonderland exmaple) there was and sometimes is "null". With other clippings files (or in most cases) like this one:
**Input file:** 
[One Up on Wall Street - Peter Lynch & John Rothchild (952)-annotation-2022-03-07_14_02_47.txt](https://github.com/wangandi520/ClippingsToMarkdown/files/8197941/One.Up.on.Wall.Street.-.Peter.Lynch.John.Rothchild.952.-annotation-2022-03-07_14_02_47.txt)

**Output file (result):**
[One Up on Wall Street - Peter Lynch & John Rothchild (952)-annotation-2022-03-07_14_02_47.md](https://github.com/wangandi520/ClippingsToMarkdown/files/8197942/One.Up.on.Wall.Street.-.Peter.Lynch.John.Rothchild.952.-annotation-2022-03-07_14_02_47.md)

For some reason, the Book and Author heading doesn't show up on this clippings file (input), like the one with "Alice in Wonderland" book.  

Is there a way to include a simple logic like such:

If "null" then leave blank AND if author is included, post that. So the results would be:

**In case of "null"**
Book: Alice's Adventures in Wonderland
Author:

**or if an author is available:** 
Book: One Up on Wall Street
Author: Peter Lynch & John Rothchild

Also on line 55 there's a mistake (not sure if that has an impact on the code itself). It should be "showAuthor" not "showAuthoer".

**Comment by wangandi520** [comment]
try new update, your new file looks a litte different

**Comment by zenminimalist** [comment]
Perfect. Thanks! Now both work as expected. 

Is there a way to remove the numbers at the end of the book? e.g. (952) Not, sure if Calibre or the readings app or BOOX adds this to the book as an ID or something.

Would that be -5 because (952) is 5 characters long? `outputfile.append('#' + each[18:-5] + '\n\n')` <-- code line 53?

**Comment by wangandi520** [comment]
yeah, -8 is ok, because '  (952)>>' is 8 length from end

**Comment by zenminimalist** [comment]
Ah yeah, right! 

In case anybody in the future wants the same here' the code snippet I changed:

`for each in filereadlines:
        if each.startswith('Reading Notes'):
            # bookname:
            outputfile.append('#' + each[18:-8] + '\n\n')
            startIndex = each.find('<') + 2
            outputfile.append('**Book:** ' + each[startIndex:-7] + '\n')
            if(filereadlines[count + 1] != "null" and showAuthor):`

Thanks again for your awesome help & support!
