### ISSUE TITLE
0 byte MD file (BooxLocalInternational.py) highlights from BOOX Note Air 2 (v3.2) default BOOX Reader app

### ISSUE THREAD

**Issue by zenminimalist** [wangandi520/ClippingsToMarkdown#2]
I have a BOOX Note AIr 2 and just exported my highlights (see file attached) with the standard BOOX reader app. 

[myfile.txt](https://github.com/wangandi520/ClippingsToMarkdown/files/8196787/myfile.txt)

The conversion resulted in a md file with 0 byte. I got **no** errors. I used the "BooxLocalInternational.py". 

Any ideas what the problems might be? Let me know if you need more info. :)

**Comment by wangandi520** [comment]
boox often change the output format, please give me a .txt with more than 2 highlight blocks in a book, maybe i can write a new script for you

**Comment by wangandi520** [comment]
or try BooxLocalInternational_anotherVersion.py

**Comment by zenminimalist** [comment]
Thanks, but the BooxLocalInternational_anotherVersion.py is  anHTML file. 

` File "/Users/David/Dropbox/Apps/Kindle Tools/ClippingsToMarkdown/BooxLocalInternational_anotherVersion.py", line 7
    <!DOCTYPE html>
    ^
SyntaxErro`

I'm assuming you must have copied the wrong file?

`boox often change the output format`

Yeah, that's stupid. I might just send BOOX support a message about that. There's no reason why they should change the format of the annotations...🤷🏼‍♂️ If you have examples of this, I'd be happy to include them in my support ticket to them 😌

**Comment by zenminimalist** [comment]
Just a quick update. It seems to work. Not sure what the problem was. However, this seems to be related to[ Issue 1](https://github.com/wangandi520/ClippingsToMarkdown/issues/1). I'll close this issue and post it in #1
