### ISSUE TITLE
请教一下关于静读天下导出的 .mrexpt 文件内容如何解读？

### ISSUE THREAD

**Issue by Geo123abc** [wangandi520/ClippingsToMarkdown#4]
一直想做一个静读天下高亮笔记（.mrexpt）的导入导出工具以便于实现和calibe高亮进行“无损转换”，但是一直搞不懂静读天下做高亮的算法以及 .mrexpt 文件内容的解读，不知道您对 .mrexpt 文件了解吗？比如这一段

```md

回归投资的本质，把许多简单的概念还原到它本来的含义，始终抱有一种朴素的追求真理的精神，坚持常识。<BR>
0
0
0
#
7
价值
/sdcard/Download/books/Jia Zhi - Zhang Lei.mobi
/sdcard/download/books/jia zhi - zhang lei.mobi
13
0
165
38
-3368512
1603354482253

```

我只知道最后一行“1603354482253”是一个时间戳，其它几行的含义是什么啊？

**Comment by wangandi520** [comment]
000#这四行好像是每一部分的最后，不是开头。我暂时也只转换了时间和标注，38这行应该是标注的长度，搜到一篇你看看最下面的回复https://github.com/davidfor/calibre-annotations/issues/19

**Comment by Geo123abc** [comment]
> 000#这四行好像是每一部分的最后，不是开头。我暂时也只转换了时间和标注，38这行应该是标注的长度，搜到一篇你看看最下面的回复[davidfor/calibre-annotations#19](https://github.com/davidfor/calibre-annotations/issues/19)

哈哈，那个issue也是我问的，不过现在重新看，又有新发现，谢谢回复
